clear;
clc;
filename = 'test';
fprintf('Loading bvh %s...\n',filename);
[skeleton, time, fps, fname] = loadbvh(filename);
save('skeleton.mat','skeleton');
fprintf('Applying Sgolay...\n');
SGF_Rotations = ApplySgolay('Skeleton',skeleton,3,5,0);
fprintf('Exporting new bvh...\n');
ExportToBvh(SGF_Rotations, filename);
fprintf('Done!\n');